### ISSUE TITLE
openSpineItemElementCfi/openSpineItemElementId opens wrong page if html is already open

### ISSUE THREAD

**Issue by nandita121189** [readium/readium-shared-js#384]
This issue is coming only in scroll auto mode (reflowable view)

The issue seems to be in function `getPageForElementCfi()` (`cfi_navigation_logic.js`) that returns wrong `pageIndex`. This function internally calls function `findPageByRectangles().` The value of "left" in `clientRectangles `variable comes wrong when html that is already open and user is not on first page.

**Comment by nandita121189** [comment]
Hello @JCCR,

I noticed that in  `getVisibleContentOffsets()` in `cfi_navigation_logic.js`, the following code was removed in one of the commits 99640b81dde92c153380bf0a57304e58279a650f

```
 return {
            left: (options.paginationInfo ? options.paginationInfo.pageOffset : 0)
                * (isPageProgressionRightToLeft() ? -1 : 1)
        };
```

If I replace the last return statement 
```
return {
            top: 0,
            left: 0
        };
```
in the current function  `getVisibleContentOffsets()`, with the code removed in the above commit
```
 return {
            left: (options.paginationInfo ? options.paginationInfo.pageOffset : 0)
                * (isPageProgressionRightToLeft() ? -1 : 1)
        };
```
, then the issue seems to be resolved, but I do not understand why that code was removed in the first place and what will be the regression if I apply the fix I suggested. Could you please guide me with it and make changes in the library itself so that it is resolved for future users as well.

**Comment by JCCR** [comment]
Acknowledged. Thanks for the report.

**Comment by danielweck** [comment]
Similar? https://github.com/readium/readium-js-viewer/issues/404

**Comment by danielweck** [comment]
Related? https://github.com/readium/readium-shared-js/issues/261

**Comment by nandita121189** [comment]
I am not sure about #404, but #261 is definitely the same issue as openSpineItemElementCfi() internally calls `Reflowable_view.openPage()` function.

**Comment by danielweck** [comment]
Fixed the regression bug via: https://github.com/readium/readium-shared-js/commit/9322c0afa3918db66c8e9f669377d9eca4975948
Please let us know how it goes in your tests.

**Comment by nandita121189** [comment]
Hi @danielweck ,

I just checked your solution on develop branch, although the bug is fixed now but it has a huge regression issue. If you notice the localstorage(of browser) you will see that the object storing last visited location of book i.e.`idref` and `contentCFI` has **null** **contentCFI**. 
Basically , `readium.reader.bookmarkCurrentPage()` is the function that has been affected by your above mentioned latest commit.

If I revert only the changes done in above mentioned commit then it behaves well as before. 

Can you please verify the same at your end.

Thanks

**Comment by danielweck** [comment]
Indeed!!

**Comment by danielweck** [comment]
Thank you very much for bringing this up @nandita121189 
I fixed the previous fix using a hacky fix: https://github.com/readium/readium-shared-js/commit/701e5900e0d47259f213ac7e4443854b353e0dbf

@JCCR any idea why "CFI navigation logic" `getVisibleContentOffsets()` works with some consumer code, but not some other? I temporarily fixed the `pageIndex` issue by locally patching the usage of `getVisibleContentOffsets()`, otherwise the change negatively affects other usages (such as bookmarking / "get visible element" functions).

**Comment by danielweck** [comment]
Related: https://github.com/readium/readium-js-viewer/issues/616

**Comment by nandita121189** [comment]
Hello @danielweck ,
Is the hacky fix https://github.com/readium/readium-shared-js/commit/701e5900e0d47259f213ac7e4443854b353e0dbf applied by you supposed to fix both the original issue and the regression issue ?
Coz I am still getting the above mentioned regression issue !

**Comment by danielweck** [comment]
No regression bug in the TravisCI-deployed build (from the `develop` branch):
https://readium.firebaseapp.com/?epub=epub_content%2Faccessible_epub_3&goto=%7B%22idref%22%3A%22id-id2635343%22%2C%22elementCfi%22%3A%22%2F4%2F2%5Bbuilding_a_better_epub%5D%2F10%2F28%2F14%2C%2F1%3A267%2C%2F1%3A268%22%7D
(above link should reference the `a` character of `accessibility` word, just before the sentence `And if you really don’t know and can’t find an answer, ask.`)

**Comment by danielweck** [comment]
PS: tested on Chrome and Firefox on OSX (Safari kinda works, but has some inconsistencies when refreshing the page).

**Comment by JCCR** [comment]
Sorry about my lack of response @nandita121189 @danielweck 
I finally have a chance to look into this

**Comment by nandita121189** [comment]
@danielweck Yes I just checked again it works for me too. As of now I didn't find the regression issues.

**Comment by danielweck** [comment]
@nandita121189  Good to know, thanks!

Thank you @JCCR for finding time to take a look at this issue.

**Comment by nandita121189** [comment]
Hello @danielweck ,

I just checked and noticed that although `openSpineItemElementId` is working fine this issue seems to be partially fixed as  `openSpineItemElementCfi` function is still not working correctly. 

Could you please check and reopen the issue.

Thanks.

**Comment by sercanl** [comment]
Hi,
Is this fix available on version 0.28?

**Comment by danielweck** [comment]
YEs
